GTESTER = gtester

TEST_PROGS =

test: $(TEST_PROGS)
	@test -z "$(TEST_PROGS)" || \
	 $(GTESTER) --verbose $(TEST_PROGS)

test-gdb: $(TEST_PROGS)
	@test -z "$(TEST_PROGS)" || \
	 for test_prog in $(TEST_PROGS) ; do \
	   $(GTESTER) --verbose $$test_prog || { \
	     libtool --mode=execute gdb --ex "run --verbose" $$test_prog ; \
	     exit 1 ; \
	   } \
	 done

generate-report: $(TEST_PROGS)
	@test -z "$(TEST_PROGS)" || \
	 $(GTESTER) $(GTESTER_ARGS) $(TEST_PROGS)
