GTESTER = gtester

TEST_PROGS =

test: $(TEST_PROGS)
	@test -z "$(TEST_PROGS)" || \
	 G_SLICE=debug-blocks $(GTESTER) --verbose $(TEST_PROGS)

test-gdb: $(TEST_PROGS)
	@test -z "$(TEST_PROGS)" || \
	 for test_prog in $(TEST_PROGS) ; do \
	   G_SLICE=debug-blocks $(GTESTER) --verbose $$test_prog || { \
	     G_SLICE=debug-blocks \
	       libtool --mode=execute gdb --ex "run --verbose" $$test_prog ; \
	     exit 1 ; \
	   } \
	 done

test-valgrind: $(TEST_PROGS)
	@test -z "$(TEST_PROGS)" || \
	 for test_prog in $(TEST_PROGS) ; do \
	   if test -e vgdump-$$test_prog; then \
	     unlink vgdump-$$test_prog; \
	   fi ; \
	   G_SLICE=always-malloc G_DEBUG=gc-friendly,resident-modules \
	     libtool --mode=execute valgrind --leak-check=full \
	     --leak-resolution=high --num-callers=20 \
	     --log-file=vgdump-$$test_prog $$test_prog ; \
	 done

test-callgrind: $(TEST_PROGS)
	@test -z "$(TEST_PROGS)" || \
	 for test_prog in $(TEST_PROGS) ; do \
	   if test -e cgdump-$$test_prog; then \
	     unlink cgdump-$$test_prog; \
	   fi ; \
	   libtool --mode=execute valgrind --tool=callgrind \
	     --callgrind-out-file=cgdump-$$test_prog \
	     --log-file=/dev/null $$test_prog ; \
	 done

generate-report: $(TEST_PROGS)
	@test -z "$(TEST_PROGS)" || \
	 G_SLICE=debug-blocks $(GTESTER) $(GTESTER_ARGS) $(TEST_PROGS)

CLEANFILES = vgdump-*

.PHONY: test test-gdb test-valgrind test-callgrind generate-report
